services:
  db:
    image: postgres:16
    container_name: planner_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: planner
      POSTGRES_PASSWORD: planner
      POSTGRES_DB: planner
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  db_test:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: coursework_test
    ports:
      - "5433:5432"

volumes:
  db_data:
